// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserSaver creates a new instance of UserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSaver {
	mock := &UserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserSaver is an autogenerated mock type for the UserSaver type
type UserSaver struct {
	mock.Mock
}

type UserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSaver) EXPECT() *UserSaver_Expecter {
	return &UserSaver_Expecter{mock: &_m.Mock}
}

// SaveUser provides a mock function for the type UserSaver
func (_mock *UserSaver) SaveUser(ctx context.Context, username string) (int64, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserSaver_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type UserSaver_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserSaver_Expecter) SaveUser(ctx interface{}, username interface{}) *UserSaver_SaveUser_Call {
	return &UserSaver_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, username)}
}

func (_c *UserSaver_SaveUser_Call) Run(run func(ctx context.Context, username string)) *UserSaver_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSaver_SaveUser_Call) Return(n int64, err error) *UserSaver_SaveUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserSaver_SaveUser_Call) RunAndReturn(run func(ctx context.Context, username string) (int64, error)) *UserSaver_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}
