all: false
dir: 'mocks'
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  mini-blog/internal/mini-blog/handlers/users/registration:
    config:
      all: true
      filename: UserSaver.go
