services:
  db:
    image: postgres:17
    container_name: mini_blog_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mini_blog_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    volumes:
      - ..:/app
    working_dir: /app/cmd/mini-blog
    command: ["go", "run", "main.go"]

volumes:
  db_data:

